<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="Tlaloc Alvarez" content="" />
        <title>cdcmx challenge 2020</title>  <!-- TITULO DE PESATAÑA DE LA WEB-->
        <link rel="icon" type="image/x-icon" href="assets/img/icon-cov.ico" />  <!-- ICONO DE LA PESTAÑA DE LA WEB-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
    
    
           <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-primary fixed-top" id="sideNav"> <!--WARNING CAMBIAR navbar-light-(navbar-dark) correct-->
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">cdcmx challenge </span>        <!-- TITULO DEL SLIDEBAR O SELECTOR DE MENU-->
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="assets/img/cdcmx.png" alt="" /></span> <!-- FOTO PARA PERFIL DEL MENU-->
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#intro">INTRO</a></li>  <!-- TITULO INTRO DEL MENU-->
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#uno">PCR</a></li> <!-- TITULO UNO DEL MENU-->
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#dos">SEGUNDO TITULO</a></li> <!-- TITULO DOS DEL MENU-->
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#tres">TERCER TITULO</a></li> <!-- TITULO TRES DEL MENU-->
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#cuatro">CUARTO TITULO</a></li> <!-- TITULO CUATRO DEL MENU-->
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#cinco">QUINTO TITULO</a></li> <!-- TITULO CINCO DEL MENU-->
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team">TEAM</a></li> <!-- TITULO TEAM DEL MENU-->
                </ul>
            </div>
        </nav>
        
        
        
        
        <!-- CONTENIDO DE LA PAGINA-->
        <div class="container-fluid p-0">
        
        
              <!-- ENCABEZADO DE LA PAGINA-->
            <section class="resume-section" id="intro"> <!-- COLOCAR BOTON DINAMICO INTRO-->
                <div class="resume-section-content">
                    <h1 class="mb-0">
                        Pruebas diagnósticas de COVID-19 <!-- PALABRA CLAVE AL INICIO DEL TITULO-->
                        <span class="text-primary">Comparando PCR y ELISA</span>  <!-- TITULO PRINCIPAL-->
                    </h1>
                    
                    
                    <div class="subheading mb-5">
                        Proyecto final de clubes de ciencia México challenge 2020 <!-- SUBTITULO PRINCIPAL-->
                        <a href="https://www.clubesdeciencia.mx/CdeCMx/Challenge">Rules and guidelines here!</a>   <!-- AÑADIR LINK A PAGINA DE CLUBES-->
                    </div>
                    
                    <p class="lead mb-5"> Este documento presenta una propuesta de una pagina web para que pueda ser utilizada
                        por los los cluberos, si deciden crearla por este método aprenderan un poco de HTML de una forma facil y practica, unicamente 
                        deben modificar el texto y las etiquetas que aparecen en el archivo index.html que se encuentra en el repositorio de esta pagina web.
                        Aqui tienen una alternativa para crear su propio sitio. pueden hacer copy-page de las lineas de codigo que aparecen en este index
                        para añadir los elementos de su pagina web o bien a manera de ejemplo para saber cuales son los comandos para añadir elementos y 
                        usarlos en su propia pagina. esta pagina contiene elementos como titulos, pestañas deslizables, imagenes y videos de youtube. 
                        Todos los elementos audivisuales se tendran que subir a la carpeta assets/img/ y unicamente colocar la ruta donde 
                        se quiera añadir el elemento. 10/08/2020. </p>  <!-- AÑADIR TEXTO DE INTRODUCCION-->
                        
                        
                        
                        
             <!-- TITULOS Y SUBTEMAS-->
             
             
             
             
             <!-- PRIMER TITULO-->
                <section class="resume-section" id="uno"> <!-- COLOCAR BOTON DINAMICO UNO-->
                <div class="resume-section-content">
                    <h2 class="mb-5">Técnica de reacción en cadena de polimerasa (PCR)</h2>  <!-- NOMBRE DEL PRIMER TITULO-->
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0">¿Que es y como funcionan las PCR?</h3> <!-- NOMBRE DEL PRIMER SUBTITULO-->
                            <div>La reacción en cadena de la polimerasa (conocida como PCR por sus siglas en inglés, Polymerase Chain Reaction) 
                            es un método de análisis de ácidos nucleicos para producir grandes cantidades de un fragmento específico de DNA de 
                            secuencia y longitud definida a partir de una pequeña cantidad de material inicial a la que llamamos “muestra” (Sánchez, 2016).
                            Esta, se calienta y se enfría repetidamente para que enzimas sintetizadoras de DNA hagan millones de copias de la secuencia del 
                            virus y a cada una de ellas se le adhieren moléculas fluorescentes que nos confirman o niegan la existencia del virus en la 
                            muestra a partir de la luz emitida (Cárdenas et al., 2020).</div> <!-- INSERTAR TEXTO-->
                            
                        </div>
    
    
    theme: jekyll-theme-cayman 
